#!/usr/bin/env bash

if [ -f signals.shinc ]; then
  source signals.shinc
else
  source /features/bash/signals.shinc
fi

if [ -f timers.shinc ]; then
  source timers.shinc
else
  source /features/bash/timers.shinc
fi

signals close
timers close


