#!/usr/bin/env bash

if [ -f signals.shinc ]; then
  source signals.shinc
else
  source /features/codeship-bash/signals.shinc
fi

if [ -f timers.shinc ]; then
  source timers.shinc
else
  source /features/codeship-bash/timers.shinc
fi

signal bob present && echo bob is present || echo bob is not present
wait_for_signal bob timer with 1000 && echo signaled || echo not signaled



